apiVersion: v1
kind: ServiceAccount
metadata:
  name: expenseflow-api
  namespace: expenseflow-staging
  labels:
    app: expenseflow-api
    environment: staging
  annotations:
    azure.workload.identity/client-id: ""
