apiVersion: v1
kind: Service
metadata:
  name: expenseflow-api
  namespace: expenseflow-dev
  labels:
    app: expenseflow-api
    app.kubernetes.io/name: expenseflow-api
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: expenseflow
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: expenseflow-api
